//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicSmth
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concerts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Concerts()
        {
            this.Tracked_Concerts = new HashSet<Tracked_Concerts>();
        }
    
        public int ID_Concert { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_Band { get; set; }
        public string Discription { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ID_Place { get; set; }
        public Nullable<decimal> Lowest_Price { get; set; }
        public Nullable<decimal> Highest_Price { get; set; }
    
        public virtual Bands Bands { get; set; }
        public virtual Places Places { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tracked_Concerts> Tracked_Concerts { get; set; }
    }
}
