//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicSmth
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photos
    {
        public int ID_Photo { get; set; }
        public Nullable<int> ID_User { get; set; }
        public byte[] Photo { get; set; }
    }
}
